version: '3.8'

services:
  web-01:
    image: jonathan216/web_infra_lab:web-01
    container_name: web-01
    command: bash -c "gunicorn -w 4 -b 0.0.0.0:8000 app:app"
    ports:
      - "8001:8000"
    restart: always
    networks:
      - webnet

  web-02:
    image: jonathan216/web_infra_lab:web-02
    container_name: web-02
    command: bash -c "gunicorn -w 4 -b 0.0.0.0:8000 app:app"
    ports:
      - "8002:8000"
    restart: always
    networks:
      - webnet

  lb-01:
    image: jonathan216/web_infra_lab:lb-01
    container_name: lb-01
    ports:
      - "8080:80"
    depends_on:
      - web-01
      - web-02
    restart: always
    networks:
      - webnet

networks:
  webnet:
